# Generated by Django 5.2.4 on 2025-08-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
