# Generated by Django 5.2.4 on 2025-08-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshop", "0002_alter_book_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
